// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (t *Tweet) LikedUsers(ctx context.Context) (result []*User, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = t.NamedLikedUsers(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = t.Edges.LikedUsersOrErr()
	}
	if IsNotLoaded(err) {
		result, err = t.QueryLikedUsers().All(ctx)
	}
	return result, err
}

func (u *User) LikedTweets(ctx context.Context) (result []*Tweet, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = u.NamedLikedTweets(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = u.Edges.LikedTweetsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = u.QueryLikedTweets().All(ctx)
	}
	return result, err
}
